require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'emailTest' do

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'emailTestTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  pre_install do |installer|
    $RNMBGL.pre_install(installer)
    # ... other pre install hooks
  end
  post_install do |installer|
    $RNMBGL.post_install(installer)
    # ... other post install hooks
  end
end

target 'emailTest-tvOS' do
  # Pods for emailTest-tvOS

  target 'emailTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
